FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install prisma @prisma/client
COPY prisma ./prisma
RUN npx prisma generate
EXPOSE 5555
CMD ["npx", "prisma", "studio", "--port", "5555", "--hostname", "0.0.0.0"]
